### ISSUE TITLE
Allow for page break modifiers in content by convention

### ISSUE THREAD

**Issue by lmajano** [scottsteinbeck/commandbox-gitbook#22]
Right now there is no way to denote a page break and it is needed to avoid nasty whitespace.  Use the convention like `---` to denote a page break.  If you see three of this with breaks, around it, then that's a page break.

```
content here

---

break was up there
```

**Comment by bdw429s** [comment]
I'm not sure how I feel about this.  Can you point out some examples of where you think there should be a page break and maybe we can come up with some heuristics to auto-detect those scenarios.

**Comment by lmajano** [comment]
If you export the modern cfml book you will see in several sections where images are used that white spacing is used and it is horrible. In a traditional book that you send to print you want complete control of breaks for pagination and chapter designation.

Just checkout the MVC section of the book. It looks horrible in pdf.

If you had a way to demarcate a page break this resolves all issues an author would have with auto page breaks which are not good.

As an author I want full page break control.

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057

________________________________

**Comment by bdw429s** [comment]
Right, so instead of just saying things "look horrible", please give some _specific_ examples like I asked for already.  Honestly, I don't think the MVC section looks that bad.  Now, you do have a ton of absolutely huge images which are going to fall to the next page simply because they don't fit.

Actually, you know what?  You _do_ already have control over page breaks.  Just create a separate page in Gitbook!  That will solve your issue right there.  But really, just give some examples of where you think a page break should have fallen and we may be able to come up with some basic rules to help make it look better automatically.  Also, once we convert this to use Flying Saucer in Lucee 5.3, we should have even better widow and orphan control with the new CSS features available.

**Comment by scottsteinbeck** [comment]
fixed. the convention is a paragraph line with exactly 3 dashes `---`

**Comment by lmajano** [comment]
💥

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057
________________________________
